fix: remove `noEmit` property from tsconfig because of errors in release workflow
reference for error: Error: tsconfig.json(13,9): error TS5053: Option 'emitDeclarationOnly' cannot
be specified with option 'noEmit'.    at makeError
(file:///home/runner/work/simple-observability/simple-observability/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
at handlePromise
(file:///home/runner/work/simple-observability/simple-observability/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async default
(file:///home/runner/work/simple-observability/simple-observability/node_modules/.pnpm/@semantic-release+npm@10.0.6_semantic-release@21.1.2_typescript@5.1.6_/node_modules/@semantic-release/npm/lib/publish.js:30:5)
at async validator
(file:///home/runner/work/simple-observability/simple-observability/node_modules/.pnpm/semantic-release@21.1.2_typescript@5.1.6/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
at async
file:///home/runner/work/simple-observability/simple-observability/node_modules/.pnpm/semantic-release@21.1.2_typescript@5.1.6/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
at async Promise.all (index 0)    at async next
(file:///home/runner/work/simple-observability/simple-observability/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:15:44)
{  shortMessage: 'Command failed with exit code 2: npm publish
/home/runner/work/simple-observability/simple-observability --userconfig
/tmp/719a70f90d2adfd5966f6204d1407bef/.npmrc --tag latest --registry https://registry.npmjs.org/',
command: 'npm publish /home/runner/work/simple-observability/simple-observability --userconfig
/tmp/719a70f90d2adfd5966f6204d1407bef/.npmrc --tag latest --registry https://registry.npmjs.org/',
escapedCommand: 'npm publish "/home/runner/work/simple-observability/simple-observability"
--userconfig "/tmp/719a70f90d2adfd5966f6204d1407bef/.npmrc" --tag latest --registry
"https://registry.npmjs.org/"',  exitCode: 2,  signal: undefined,  signalDescription: undefined,
stdout: '
' +    '> simple-observability@1.0.0 prepublishOnly
' +    '> npm run build
' +    '
'
+    '
' +    '> simple-observability@1.0.0 build
' +    '> npm run clean && npm run build:types
&& npm run build:js
' +    '
' +    '
' +    '> simple-observability@1.0.0 clean
' +    '>
rimraf dist
' +    '
' +    '
' +    '> simple-observability@1.0.0 build:types
' +    '> tsc
--emitDeclarationOnly
' +    '
' +    "tsconfig.json(13,9): error TS5053: Option
'emitDeclarationOnly' cannot be specified with option 'noEmit'.",  stderr: 'npm error code 2
' +
'npm error path /home/runner/work/simple-observability/simple-observability
' +    'npm error
command failed
' +    'npm error command sh -c npm run build
' +    '
' +    'npm error A
complete log of this run can be found in:
/home/runner/.npm/_logs/2024-10-27T03_41_27_411Z-debug-0.log',  cwd:
'/home/runner/work/simple-observability/simple-observability',  failed: true,  timedOut: false,
isCanceled: false,  killed: false,  pluginName: '@semantic-release/npm' ELIFECYCLE  Command failed
with exit code 1.}Error: Process completed with exit code 1.